package li.tmj.db.model.base;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class State extends Data {
	private String nameDeu;
//	protected int id=0; // id generated by the external DB and then always >0
	
	@Id @GeneratedValue(strategy=GenerationType.AUTO) @Override
	public int getId() {
		return id;
	}
//	@Override
//	public void setId(int id) {
//		this.id = id;
//	}
	
	public State() {
		
	}
	
	public State(int id) {
		setId(id);
	}

	public String getNameDeu() {
		return nameDeu;
	}
	public void setNameDeu(String nameDeu) {
		this.nameDeu = nameDeu;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((changed == null) ? 0 : changed.hashCode());
		result = prime * result + ((created == null) ? 0 : created.hashCode());
		result = prime * result + id;
		result = prime * result + ((nameDeu == null) ? 0 : nameDeu.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		State other = (State) obj;
		if (changed == null) {
			if (other.changed != null)
				return false;
		} else if (!changed.equals(other.changed))
			return false;
		if (created == null) {
			if (other.created != null)
				return false;
		} else if (!created.equals(other.created))
			return false;
		if (id != other.id)
			return false;
		if (nameDeu == null) {
			if (other.nameDeu != null)
				return false;
		} else if (!nameDeu.equals(other.nameDeu))
			return false;
		return true;
	}
	@Override
	public String toString() {
		return "State [id=" + id + ", changed=" + changed + ", created=" + created + ", nameDeu=" + nameDeu + "]";
	}
	
}
